devicefinder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
        path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.Home.as_view(), name='home'),
  path('hospitals/', views.hospitals, name='hospitals'),
  path('hospitals/<int:hospital_id>/', views.hospitals_detail, name='hospitals_detail'),
  path('hospitals/create/', views.HospitalCreate.as_view(), name='hospitals_create'),
  path('hospitals/<int:pk>/update/', views.HospitalUpdate.as_view(), name='hospitals_update'),
  path('hospitals/<int:pk>/delete/', views.HospitalDelete.as_view(), name='hospitals_delete'),
  path('hospitals/<int:hospital_id>/add_device/', views.add_device, name='add_device'),
  path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

DEVICES = (
  ('M', 'Montage'),
  ('N', 'Neuro Combo 1.5mm'),
  ('Q', 'Rib Fix Advantage'),
  ('R', 'Rib Fix Blu'),
  ('S', 'Sternalock Blu'),
  ('T', 'Thin Flap Neuro 1.5mm'),
  ('U', 'Trauma One'),
)

STATUS = (
  ('C', 'Consignment'),
  ('L', 'Loaner'),
)
  
class Hospital(models.Model):
  name = models.CharField('Hospital Name', max_length=100)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  def __str__(self):
    return self.name
  def get_absolute_url(self):
    return reverse('hospitals')

class Device(models.Model):
  name = models.CharField(
    max_length=1,
    choices=DEVICES,
    default=DEVICES[0][0]
    )
  status = models.CharField(
    max_length=1,
    choices=STATUS,
    default=STATUS[0][0],
  )
  hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
  def __str__(self):
    return str(self.name)

main_app/forms.py
from django.forms import ModelForm
from .models import Device

class DeviceForm(ModelForm):
  class Meta:
    model = Device
    fields = ['name', 'status']

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Hospital
from .forms import DeviceForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin


class HospitalCreate(LoginRequiredMixin, CreateView):
  model = Hospital
  fields = '__all__'
  def form_valid(self, form):
    form.instance.user = self.request.user  
    return super().form_valid(form)

class HospitalUpdate(LoginRequiredMixin, UpdateView):
  model = Hospital
  fields = '__all__'

class HospitalDelete(LoginRequiredMixin, DeleteView):
  model = Hospital
  success_url = '/hospitals/'

class Home(LoginView):
  template_name = 'home.html'

@login_required 
def hospitals(request):
  hospitals = Hospital.objects.filter(user=request.user)
  return render(request, 'hospitals/index.html', { 'hospitals': hospitals })

@login_required 
def hospitals_detail(request, hospital_id):
  hospital = Hospital.objects.get(id=hospital_id)
  device_form = DeviceForm()
  return render(request, 'hospitals/detail.html', { 'hospital': hospital, 'device_form': device_form })

@login_required 
def add_device(request, hospital_id):
  form = DeviceForm(request.POST)
  if form.is_valid():
    new_device = form.save(commit=False)
    new_device.hospital_id = hospital_id
    new_device.save()
  return redirect('hospitals_detail', hospital_id=hospital_id)

@login_required 
def hospitals_create(request, hospital_id):
  hospital = Hospital.objects.get(id=hospital_id)
  return render(request, 'hospitals/detail.html', { 'hospital': hospital })

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('hospitals')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href=""
  >
  <title>Device Finder</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'hospitals' %}">My Hospitals</a></li>
        {% else %}
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home</title>
</head>
<body>
  {% extends 'base.html' %}
  {% load static %}

  {% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
  {% endblock %}
  
{% block content %}
  
  {% if not user.is_authenticated %}

  <section class="logo-container">
    <h1 class="logo-text">Welcome to Med Device Helper!</h1>
  </section>

 <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <div class='btn-login'> 
        <button type="submit" class="btn warn">Login</button>
        <button class="btn warn">
          <a href="{% url 'signup' %}">Signup</a>
        </button>
      </div>
    </form>
  </section>

{% elif user.is_authenticated %}

<section class="logo-container">
  <h1 class="logo-text">Welcome to Med Device Helper!</h1>
</section>

<section>
    <div class='btn-logout'> 
      <button type="submit" class="btn warn"><a href="{% url 'logout' %}">Logout</a></button>
    </div>
</section>

{% endif %}
  

  {% endblock %}
  
</body>
</html>

main_app/templates/hospitals/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/hospitals/hospital-detail.css' %}"
/>
{% endblock %}

{% block content %}

<section class="hospital-container">
  <div class="hospital-details"> 
    <h1>{{ hospital.name }}</h1>
  </div>
  <div class="hospital-actions"> 
    <a href="{% url 'hospitals_update' hospital.id %}" class="btn warn">Edit</a>
    <a href="{% url 'hospitals_delete' hospital.id %}" class="btn danger">Delete</a>
  </div>

</section>

<div class="device-container">
  <section class="devices">
    <div class="subsection-title">
      <h2>Devices</h2>
    </div>
    <h3>Add a Device</h3>
      <form
        action="{% url 'add_device' hospital.id %}"
        method="post" 
        class="subsection-content"
      >
        {% csrf_token %}
        {{ device_form.as_p }}
        <button type="submit" class="btn submit">Add Device</button>
      </form>
    {% if hospital.device_set.all.count %}
    <table>
      <thead>
        <tr><th>Device Name</th><th>Status</th></tr>
      </thead>
      <tbody>
        {% for device in hospital.device_set.all %}
          <tr>
            <td>{{device.get_name_display}}</td>
            <td>{{device.get_status_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <div class="subsection-content">
        <p>{{hospital.name}} has no devices 😔</p>
      </div>
    {% endif %}
  </section>
</div>

{% endblock %}

main_app/templates/hospitals/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/hospitals/hospital-index.css' %}"
/>
{% endblock %}

{% block content %}

<section class="my-hospitals">
  <h1>My Hospitals</h1>

  <a href="{% url 'hospitals_create' %}">
    <h3>Add Hospital</h3>
  </a>
</section>

  
<section class="card-container">
  {% for hospital in hospitals %}
  <a href="{% url 'hospitals_detail' hospital.id %}">
    <div class="card">
      <div class="card-content">
        <h2 class="card-title">{{ hospital.name }}</h2>
      </div>
    </div>
  </a>  
  {% endfor %}
</section>

  {% endblock %}

  <div class="card-deck">
    {% for book in books %}
        {% include 'books/book_element.html' %}
        {% if forloop.counter|divisibleby:"5"  %}
            {# Close the current deck and start a new one %}
            </div><div class="card-deck">
        {% endif %}
    {% endfor %}
</div><!-- The final dec

main_app/templates/main_app/hospital_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Hospital?</h1>
</div>
<h2>Are you sure you want to delete {{ hospital.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'hospitals_detail' hospital.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/hospital_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

{% if hospital %}
  <h1>{{ hospital.name }}</h1>
{% else %}
<div class="page-header">
  <h1>Add a Hospital</h1>
{% endif %}
</div>
<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Sign Up</h1>
 
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}